base.url=https://automationexercise.com
base.api.url=https://automationexercise.com

browser=chrome

explicit.wait=5

valid.email=mohansurya@test.com
valid.password=Mohan@1234

invalid.email=wrong@test.com
invalid.password=wrong123

user.name=Mohan
user.title=Mr
user.birth_date=1
user.birth_month=1
user.birth_year=2005
user.firstname=Mohan
user.lastname=Surya
user.company=Veeva
user.address1=Miyapur
user.address2=Hyderabad
user.country=India
user.zipcode=500001
user.state=Telangana
user.city=Hyderabad
user.mobile_number=1234567890

updated.name=Raghu
updated.title=Employee
updated.firstname=Raghu
updated.lastname=Vamshi
updated.company=Veeva Updated
updated.address1=Madhapur
updated.address2=Hyderabad
updated.mobile_number=9876543210
